export const DomainRows = [
  {
      id: 1,
      domain: 'example1.com',
      funnel: 'Sales Funnel A',
      lastUpdate: '2024-10-01',
      domainVerification: 'Verified',
  },
  {
      id: 2,
      domain: 'example2.com',
      funnel: 'Sales Funnel B',
      lastUpdate: '2024-09-28',
      domainVerification: 'Not Verified',
  },
  {
      id: 3,
      domain: 'example3.com',
      funnel: 'Sales Funnel C',
      lastUpdate: '2024-10-03',
      domainVerification: 'Pending',
  },
  {
      id: 4,
      domain: 'example4.com',
      funnel: 'Sales Funnel D',
      lastUpdate: '2024-09-30',
      domainVerification: 'Verified',
  },
  {
      id: 5,
      domain: 'example5.com',
      funnel: 'Sales Funnel E',
      lastUpdate: '2024-10-05',
      domainVerification: 'Verified',
  },
  {
      id: 6,
      domain: 'example6.com',
      funnel: 'Sales Funnel F',
      lastUpdate: '2024-09-25',
      domainVerification: 'Not Verified',
  },
  {
      id: 7,
      domain: 'example7.com',
      funnel: 'Sales Funnel G',
      lastUpdate: '2024-10-02',
      domainVerification: 'Verified',
  },
  {
      id: 8,
      domain: 'example8.com',
      funnel: 'Sales Funnel H',
      lastUpdate: '2024-09-29',
      domainVerification: 'Pending',
  },
  {
      id: 9,
      domain: 'example9.com',
      funnel: 'Sales Funnel I',
      lastUpdate: '2024-10-04',
      domainVerification: 'Verified',
  },
  {
      id: 10,
      domain: 'example10.com',
      funnel: 'Sales Funnel J',
      lastUpdate: '2024-09-27',
      domainVerification: 'Not Verified',
  },
  {
      id: 11,
      domain: 'example11.com',
      funnel: 'Sales Funnel K',
      lastUpdate: '2024-10-06',
      domainVerification: 'Verified',
  },
];
